      COMMON/REL/    SPN(3,NMAX),RELENERGY(KMAX),ESCRELCOR(KMAX),
     &               RELTSTEP(KMAX),RFLAG(KMAX),RELPOTENERGY(KMAX),
     &               GAMREL(8,KMAX),PN1ENERGY(2,KMAX),DIFFS(10),
     &               DE25(2,KMAX),GAMMAREL,PREVRELENERGY,SRELENERGY,
     &               BETAREL,DTUPN,VOVERC,CLIGHTPN,CLIN,SPNMAG,RELSUM,
     &               PREVRELPOTENERGY,PLOTTIME,IPLOTCOUNT
*      COMMON/REL_H5/ SEMI2_vec(NMAX), ECCPN_vec(NMAX), SEMI_vec(NMAX), 
*     &               ECC_vec(NMAX)
      REAL*8 RELENERGY,GAMMAREL,ESCRELCOR,RELTSTEP,PREVRELENERGY
      REAL*8 SRELENERGY,BETAREL,DTUPN,SPN,SPNMAG,PN1ENERGY
      REAL*8 VOVERC,RFLAG,CLIGHTPN,RELPOTENERGY,GAMREL,CLIN
      REAL*8 RELSUM,DIFFS,PREVRELPOTENERGY,PLOTTIME,DE25
      INTEGER IPLOTCOUNT
