*     Common block for scaling factors for output

      COMMON /scale_out/ RSCALE_OUT, MSCALE_OUT, VSCALE_OUT, RAU_OUT, 
     &     TSCALE_OUT, DAYS_OUT, FSCALE_OUT, POTSCALE_OUT, G_OUT
      REAL*8 RSCALE_OUT, MSCALE_OUT, VSCALE_OUT, RAU_OUT
      REAL*8 TSCALE_OUT, DAYS_OUT, FSCALE_OUT, POTSCALE_OUT,G_OUT
